name: Bugfix - Describe the bug to Sweep
title: 'Sweep: '
description: We notice ... behavior when ... happens instead of ...
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details about the bug
      placeholder: The bug might be in ... file