name: Feature Request
title: 'Sweep: '
description: What feature should Sweep handle? "Write an api endpoint that does "..." in the "..." file"
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details for Sweep
      placeholder: The new endpoint should use the ... class from ... file because it contains ... logic.