name: Feature Request
description: Describe a feature to Sweep
title: 'Sweep: '
description: What feature should Sweep handle?
placeholder: Write an api endpoint that does "..." in the "..." file
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details for Sweep
      placeholder: The new endpoint should use the ... class from ... file because it contains ... logic.